// Village Area (Safe Zone)
const canvasWidth = 540; // Width of village interior
const canvasHeight = 566; // Height of village interior

export const canvasConfigs = {
  // Village level - resize canvas to match wall perimeter
  canvasWidth, // Width of village interior
  canvasHeight, // Height of village interior
  width: canvasWidth,
  height: canvasHeight,
  worldWidth: canvasWidth,
  worldHeight: canvasHeight,

  playerX: 270, // Center horizontally
  playerY: 283, // Center vertically

  backgroundColor: '#478120', // Forest green
  accentColor: '#294f0c', // Darker green
};


export default {
  "worldWidth": 400,
  "worldHeight": 400,
  "canvasWidth": 400,
  "canvasHeight": 400,
  "playerX": 270,
  "playerY": 283,
  "backgroundColor": "#478120",
  "houses": 0,
  "walls": [],
  "trees": [],
  "mountains": [
    {
      "x": -24,
      "y": 165,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -14,
      "enemyCollisionY": 195,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -19,
      "y": 107,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -9,
      "enemyCollisionY": 137,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -28,
      "y": 72,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -18,
      "enemyCollisionY": 102,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -39,
      "y": 43,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -29,
      "enemyCollisionY": 73,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -22,
      "y": 18,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -12,
      "enemyCollisionY": 48,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -25,
      "y": -14,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -15,
      "enemyCollisionY": 16,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 35,
      "y": -5,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 45,
      "enemyCollisionY": 25,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 107,
      "y": 5,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 117,
      "enemyCollisionY": 35,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 160,
      "y": -10,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 170,
      "enemyCollisionY": 20,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 222,
      "y": -15,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 232,
      "enemyCollisionY": 15,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 275,
      "y": -15,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 285,
      "enemyCollisionY": 15,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 326,
      "y": -12,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 336,
      "enemyCollisionY": 18,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 339,
      "y": 27,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 349,
      "enemyCollisionY": 57,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 343,
      "y": 74,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 353,
      "enemyCollisionY": 104,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 342,
      "y": 132,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 352,
      "enemyCollisionY": 162,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 337,
      "y": 184,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 347,
      "enemyCollisionY": 214,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": -36,
      "y": 339,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": -26,
      "enemyCollisionY": 369,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 23,
      "y": 354,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 33,
      "enemyCollisionY": 384,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 82,
      "y": 355,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 92,
      "enemyCollisionY": 385,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 132,
      "y": 354,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 142,
      "enemyCollisionY": 384,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 177,
      "y": 336,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 187,
      "enemyCollisionY": 366,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 176,
      "y": 368,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 186,
      "enemyCollisionY": 398,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 216,
      "y": 358,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 226,
      "enemyCollisionY": 388,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 335,
      "y": 355,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 345,
      "enemyCollisionY": 385,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 341,
      "y": 225,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 351,
      "enemyCollisionY": 255,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 341,
      "y": 277,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 351,
      "enemyCollisionY": 307,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 345,
      "y": 327,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 355,
      "enemyCollisionY": 357,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 281,
      "y": 353,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 291,
      "enemyCollisionY": 383,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 28,
      "y": 125,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 38,
      "enemyCollisionY": 155,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 48,
      "y": 102,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 58,
      "enemyCollisionY": 132,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 82,
      "y": 47,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 92,
      "enemyCollisionY": 77,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 280,
      "y": 128,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 290,
      "enemyCollisionY": 158,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 230,
      "y": 92,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 240,
      "enemyCollisionY": 122,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 221,
      "y": 52,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 231,
      "enemyCollisionY": 82,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 175,
      "y": 37,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 185,
      "enemyCollisionY": 67,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 125,
      "y": 47,
      "width": 80,
      "height": 60,
      "type": "mountain",
      hasPortal: true,
      portalDestination: 0,
      "enemyCollisionX": 135,
      "enemyCollisionY": 77,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 20,
      "y": 52,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 30,
      "enemyCollisionY": 82,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 280,
      "y": 79,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 290,
      "enemyCollisionY": 109,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 272,
      "y": 32,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 282,
      "enemyCollisionY": 62,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 226,
      "y": 20,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 236,
      "enemyCollisionY": 50,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 229,
      "y": 138,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 239,
      "enemyCollisionY": 168,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    },
    {
      "x": 302,
      "y": 169,
      "width": 80,
      "height": 60,
      "type": "mountain",
      "hasCaveOpening": false,
      "caveOpeningDestination": null,
      "enemyCollisionX": 312,
      "enemyCollisionY": 199,
      "enemyCollisionWidth": 60,
      "enemyCollisionHeight": 30
    }
  ],
  "stalactites": [],
  "caves": [],
  "entries": [
    {
      "x": -2,
      "y": 226,
      "width": 32,
      "height": 120,
      "destinationLevel": 1,
      "destinationX": null,
      "destinationY": null,
      "type": "entry"
    }
  ]
}